<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OldFaceLee.local" ignored="0" name="Command line test" tests="6" failures="4" timestamp="15 四月 2020 05:09:57 GMT" time="4.962" errors="0">
  <testcase name="tc02" time="0.003" classname="com.ai.api.testsuite.TestSuite">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ai.api.testcase.TC02_test.runScript(TC02_test.java:37)
	at com.ai.api.testsuite.TestSuite.tc02(TestSuite.java:31)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- tc02 -->
  <testcase name="tc02" time="0.001" classname="com.ai.api.testsuite.TestSuite">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ai.api.testcase.TC02_test.runScript(TC02_test.java:37)
	at com.ai.api.testsuite.TestSuite.tc02(TestSuite.java:31)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- tc02 -->
  <testcase name="tc02" time="0.106" classname="com.ai.api.testsuite.TestSuite"/>
  <testcase name="tc01" time="0.112" classname="com.ai.api.testsuite.TestSuite"/>
  <testcase name="tc01" time="0.004" classname="com.ai.api.testsuite.TestSuite">
    <failure type="java.lang.AssertionError" message="expected [通过] but found [不通过]">
      <![CDATA[java.lang.AssertionError: expected [通过] but found [不通过]
	at com.ai.api.support.dataDriver.Check.verifyResultDataColumnValue(Check.java:21)
	at com.ai.api.testcase.TC01_test.runScript(TC01_test.java:46)
	at com.ai.api.testsuite.TestSuite.tc01(TestSuite.java:26)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- tc01 -->
  <testcase name="tc01" time="0.003" classname="com.ai.api.testsuite.TestSuite">
    <failure type="java.lang.AssertionError" message="expected [通过] but found [不通过]">
      <![CDATA[java.lang.AssertionError: expected [通过] but found [不通过]
	at com.ai.api.support.dataDriver.Check.verifyResultDataColumnValue(Check.java:21)
	at com.ai.api.testcase.TC01_test.runScript(TC01_test.java:46)
	at com.ai.api.testsuite.TestSuite.tc01(TestSuite.java:26)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- tc01 -->
</testsuite> <!-- Command line test -->
